name: Deploy Flask API to Server

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH for server access
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Connect to the server and deploy
    - name: Deploy to Server
      run: |
        # Login to server via SSH
        ssh -o StrictHostKeyChecking=no root@89.117.57.199 << 'EOF'
        
        # Ensure the project directory exists or clone the repository
        if [ ! -d "/amber/project1" ]; then
          mkdir -p /amber/project1
          git clone https://github.com/amberasif/DevOps_Practice_Task.git /amber/project1
        fi

        # Navigate to the project directory
        cd /amber/project1

        # Pull the latest changes from the repository
        git pull origin main

        # Install dependencies
        pip install -r requirements.txt

        # Build the Docker image
        docker build -t flask-api .

        # Stop and remove the old container if it exists
        docker stop flask-api || true
        docker rm flask-api || true

        # Run the new Docker container
        docker run -d -p 5000:5000 --name flask-api flask-api

        EOF
